CREATE TABLE fields(
ID SMALLINT NOT NULL AUTO_INCREMENT, 
PRIMARY KEY(ID),
Name VARCHAR(250),
Scale REAL,
StationID INT,
StationTypeID INT,
ChamberTypeID INT,
Units VARCHAR(150),
AQT_Name VARCHAR(50),
TypeID INT,
Comments VARCHAR(350)
);

CREATE TABLE opc_data(
ID SMALLINT,
Time TIMESTAMP,
Value FLOAT);


CREATE TABLE `opc_data` (
  `ID` smallint(6) DEFAULT NULL,
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAM
P,
  `Value` float DEFAULT NULL,
  KEY `id_index` (`ID`),
  KEY `timestamp_index` (`Time`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |



CREATE TABLE opc_data_mem(
ID SMALLINT,
Time TIMESTAMP,
Value FLOAT) ENGINE = MEMORY DEFAULT CHARSET=latin1 ;